"""initial schema

Revision ID: e3292e332a1a
Revises: 
Create Date: 2025-06-14 14:25:57.981261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3292e332a1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polling_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbols', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_market_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_market_data_symbol'), 'raw_market_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_raw_market_data_timestamp'), 'raw_market_data', ['timestamp'], unique=False)
    op.create_table('symbol_averages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('moving_average', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbol_averages_symbol'), 'symbol_averages', ['symbol'], unique=False)
    op.create_index(op.f('ix_symbol_averages_timestamp'), 'symbol_averages', ['timestamp'], unique=False)
    op.create_table('price_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('raw_response_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['raw_response_id'], ['raw_market_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_points_symbol'), 'price_points', ['symbol'], unique=False)
    op.create_index(op.f('ix_price_points_timestamp'), 'price_points', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_points_timestamp'), table_name='price_points')
    op.drop_index(op.f('ix_price_points_symbol'), table_name='price_points')
    op.drop_table('price_points')
    op.drop_index(op.f('ix_symbol_averages_timestamp'), table_name='symbol_averages')
    op.drop_index(op.f('ix_symbol_averages_symbol'), table_name='symbol_averages')
    op.drop_table('symbol_averages')
    op.drop_index(op.f('ix_raw_market_data_timestamp'), table_name='raw_market_data')
    op.drop_index(op.f('ix_raw_market_data_symbol'), table_name='raw_market_data')
    op.drop_table('raw_market_data')
    op.drop_table('polling_jobs')
    # ### end Alembic commands ###
